# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{allejest}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maciej Bilas"]
  s.date = %q{2010-03-20}
  s.default_executable = %q{allejest}
  s.description = %q{Powiadamia e-mailem o dostępności przedmiotów na allegro.}
  s.email = %q{maciej@inszy.org}
  s.executables = ["allejest"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/allejest",
     "lib/alle_jest/mail.erb",
     "lib/allejest.rb",
     "nbproject/project.properties",
     "nbproject/project.xml",
     "spec/allejest_spec.rb",
     "spec/fixtures/allegro_canon1022_results.rss",
     "spec/fixtures/allejest.yml",
     "spec/matchers.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/maciej/allejest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{allejest}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Powiadamia e-mailem o dostępności przedmiotów na allegro}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/matchers.rb",
     "spec/allejest_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<feed_me>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<simply_useful>, [">= 0.1.6"])
      s.add_runtime_dependency(%q<pony>, [">= 0.9"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_dependency(%q<feed_me>, [">= 0.6.0"])
      s.add_dependency(%q<simply_useful>, [">= 0.1.6"])
      s.add_dependency(%q<pony>, [">= 0.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    s.add_dependency(%q<feed_me>, [">= 0.6.0"])
    s.add_dependency(%q<simply_useful>, [">= 0.1.6"])
    s.add_dependency(%q<pony>, [">= 0.9"])
  end
end

